platform :ios, '12.2'
workspace '/home/vault/demo_swift_hello_world/Demo_Hello_World/Demo_Swift_HelloWorld.xcodeproj/project.xcworkspace'
pod 'RegExCategories', '1.0'
pod 'iCarousel', '1.7.6'
pod 'FMDB', '2.3'
#pod 'CoolTable', '1.0'
#pod 'FLAnimatedImage', '1.0.14'
pod 'CorePlot', '2.3'
pod 'EGOCache', '2.0.0'
#pod 'IXKeychain', '1.0'
pod 'LxKeychain', '1.0'
pod 'JSONModel', '1.0'
pod 'Masonry', '1.0.2'
pod 'MBProgressHUD', '0.7'
